# Generated by Django 4.2.7 on 2023-11-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product', to_field='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
